close hero section #2
ReCoded-Org/capstone-turkey-giftify pull request #13
Opened 2021-08-08 21:03 UTC by busesisi

- Giftify button is functional

2021-08-09 17:05 UTC, ceyhungulbas requested changes
Eline saglik Buse! Looks really really good! 

I just saw a few teeny tiny issues:
- You just need to importing font with these code in CSS `@import url("https://fonts.googleapis.com/css2?family=Roboto&display=swap");`
- Logo goes out of range in width: 1026-1073
![resim](https://user-images.githubusercontent.com/44509662/128744080-efa7850f-dd00-45ea-852b-d4748fe58fef.png)
- The logo appears in front of text in the width range : 415-670 
![resim](https://user-images.githubusercontent.com/44509662/128745003-f99c9d12-6b5b-4dbb-9bb4-bf5ec7ef0be0.png)
- Button's width is `width: 12%;` thats why button looks asymmetric 
![resim](https://user-images.githubusercontent.com/44509662/128745301-5aeb498f-9f28-460b-84e3-25a4234d8a53.png)

2021-08-09 17:41 UTC, halitbatur commented
@busesisi please run ```yarn run fix``` and commit the changes in order for the files to be correctly indented

2021-08-10 06:47 UTC, ceyhungulbas approved these changes
Wow! I just checked and looks really good! Responsiveness is working and great. Looks good to me!

2021-08-12 17:58 UTC, halitbatur requested changes

2021-08-12 17:58 UTC, halitbatur commented on src/components/Hero/Hero.scss
> +.giftifyButton > a > button {
new line missing here

2021-08-12 17:58 UTC, halitbatur commented on src/components/Hero/Hero.jsx
> +//Button is not working from react-bootstrap
I think react css needs to be improted in the app.js in order to be able to use react-bootstrap

2021-08-12 17:58 UTC, halitbatur commented on src/components/Hero/Hero.jsx
> +            Don’t need it?
lets not use h1 here maybe an h2 would be better, since we need to only use h1 once in our website for SEO

2021-08-12 17:58 UTC, halitbatur commented on src/components/Hero/Hero.scss
> +  }
missing new line

2021-08-13 11:09 UTC, halitbatur commented
@busesisi this is failing CI tests can you fix that ?

2021-08-17 08:34 UTC, halitbatur requested changes

2021-08-17 08:34 UTC, halitbatur commented on src/components/UserProfile/UserProfile.scss
> +#userProfile {
why is there a UserProfile.scss file in this PR I think this should be in the userprofile PR not here

2021-08-18 07:53 UTC, halitbatur requested changes

2021-08-18 07:53 UTC, halitbatur commented on src/components/Hero/_test_/Hero.test.js
> +it("matches snapshot", () => {
Maybe change the name of the test to be like hero section renderd correctly

2021-08-19 08:11 UTC, halitbatur commented on src/components/Hero/Hero.jsx
> +//Button is not working from react-bootstrap
@busesisi can we fix this ?

2021-08-19 09:07 UTC, halitbatur commented
@busesisi update this branch with the latest dev branch and resolve conflicts

2021-08-19 12:53 UTC, udenizdemirbilek commented on src/App.js
>  import React from "react";
App.js looks outdated, please git pull from the remote repository

2021-08-19 13:46 UTC, halitbatur commented
@busesisi this still needs another update from the latest dev version

2021-08-19 13:53 UTC, halitbatur requested changes

2021-08-19 13:53 UTC, halitbatur commented on src/components/Hero/Hero.css
> +HTML {
do you want to target everything ? can we use smth like the *  selector I have never seen this HTML getting used

2021-08-19 13:53 UTC, halitbatur commented on src/App.js
> +          <Route exact path="/" component={Hero} />
hmm I think the Hero component just needs to be rendered inside the Home container instead of replacing it in the main route

2021-08-20 07:42 UTC, halitbatur commented
@busesisi can we get these error for the CI and CD fixed today and try to merge this PR today ?

2021-08-20 17:43 UTC, halitbatur requested changes
a few changes needs to be done and then hopefully we are ready to merge it

2021-08-20 17:43 UTC, halitbatur commented on src/App.js
> -          <Route exact path="/request-item/:id" component={RequestItem} />
this line should have not been deleted

2021-08-20 17:43 UTC, halitbatur commented on src/App.js
> +import HomePage from "./containers/HomePage/HomePage"; // eslint-disable-next-line
we dont need to disable eslint for next line since it needs to be used on line 19

2021-08-20 17:43 UTC, halitbatur commented
@busesisi good work !

2021-08-23 07:58 UTC, halitbatur approved these changes
@busesisi update this branch and its ready to be merged

2021-08-27 07:51 UTC, halitbatur approved these changes

2021-08-27 07:51 UTC, merged