Contact component
ReCoded-Org/capstone-turkey-giftify pull request #29
Opened 2021-08-17 07:18 UTC by ayshesaflo

issue #25 

Create Contact Us page that contains company contact into and a form
when form's data is submitted, data will be saved in firebase ContactUs collection

web screen
![image](https://user-images.githubusercontent.com/81983858/129680724-8d7b7192-9db5-4637-8307-aa75424ec3bc.png)

tablet screen
![image](https://user-images.githubusercontent.com/81983858/129680837-012bc4e5-1984-45c1-8562-b619a0f89046.png)

phone screen
![image](https://user-images.githubusercontent.com/81983858/129681021-9948e6bc-a1bb-48ab-bcdd-6c8793bf3562.png)

2021-08-18 20:20 UTC, ceyhungulbas requested changes
Hey Ayshe! Eline saglik, I just seen some issues:

App.js
- ContactUSPage should be inside of container

ContactUs.jsx
- line 16 there's a console.log
- typo Massege -> Message
- line 50 `<div className="contatctinfo">` typo
- line 76 `<form className="inpurForm" onSubmit={handleSubmit}>` typo

ContactUs.css
- typos in here too

ContactUSPage.jsx
- line 3 and 11 `ConactUSPage()` typo

Test:
- We should have test

Bug:
![resim](https://user-images.githubusercontent.com/44509662/129966082-44a9672c-f57b-4bf3-8136-6f37b50b5605.png)
![resim](https://user-images.githubusercontent.com/44509662/129966132-db7ec996-ae30-4aaa-86d5-4bb93fdc278a.png)

When user add so long text Message area going like endless line. I think we should change to a box.

2021-08-18 21:03 UTC, ayshesaflo commented
> * `ConactUSPage()`


The required changes have done

2021-08-19 13:05 UTC, udenizdemirbilek commented on src/App.js
> +        <ContactUSPage />
Please update App with git pull, then link ContactUSPage as a Route like [here](https://github.com/ReCoded-Org/capstone-turkey-giftify/pull/15/files#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67)

2021-08-19 13:06 UTC, udenizdemirbilek commented on src/App.js
> +import ContactUSPage from "./Container/ContactUSPage";
folder name should be "containers" instead of "Container"

2021-08-19 13:08 UTC, udenizdemirbilek commented on src/components/ContactUs/__tests__/ContactUs.test.js
> +it("matches Snapshot", () => {
please change test name

2021-08-19 13:08 UTC, udenizdemirbilek requested changes
Good work Ayshe!
I've added my comments

2021-08-20 17:42 UTC, ayshesaflo commented
@halitbatur PTAL

The required changes are done
the name of Snapshot
App is updated
The "Container" file changed to "containers"

2021-08-20 18:27 UTC, ceyhungulbas approved these changes
I checked it now. LGTM! Ellerine saglik!

- Responsiveness is working
- Functionality is working
- Test message is correct
- Folders name fixed
- App.js Router part fixed

2021-08-23 08:17 UTC, halitbatur requested changes

2021-08-23 08:17 UTC, halitbatur commented on src/App.js
> +          <Route ecactpath="/" component={Navbar} />
please remove the "ecact" word from here

2021-08-23 08:17 UTC, halitbatur commented on src/components/ContactUs/ContactUs.css
> +}
new line needed

2021-08-23 08:17 UTC, halitbatur commented on src/components/ContactUs/ContactUs.css
> +.Message {
classNames should be camelCased

2021-08-23 08:17 UTC, halitbatur commented on src/components/ContactUs/ContactUs.jsx
> +  const [inputName, setInputName] = useState("");
can we move all the inputs to an object ?

2021-08-23 08:17 UTC, halitbatur commented on src/components/ContactUs/ContactUs.jsx
> +      db.collection("contactUs").onSnapshot(function (querySnapshot) {
why are we fetching the contactUs data here if its not getting used ?

2021-08-23 08:17 UTC, halitbatur commented on src/containers/ContactUSPage/ContactUSPage.jsx
> +import ContactUs from "../../components/ContactUs/ContactUs";
please add new line after import

2021-08-23 08:17 UTC, halitbatur commented on src/containers/ContactUSPage/ContactUSPage.jsx
> +import React from "react";
file name is incorrect it should be ContactUsPage

2021-08-25 19:39 UTC, halitbatur requested changes

2021-08-25 19:39 UTC, halitbatur commented on src/App.js
> +import ContactUSPage from "./containers/ContactUsPage/ContactUsPage";
the import name is still wrong it needs to be ContactUsPage the s is not capital

2021-08-25 19:39 UTC, halitbatur commented on src/components/ContactUs/ContactUs.css
> +  }
new line between each rule please

2021-08-25 19:39 UTC, halitbatur commented on src/components/ContactUs/ContactUs.css
> +  }
new line needed between each rule

2021-08-25 19:39 UTC, halitbatur commented on src/components/ContactUs/ContactUs.css
> +  }
new line missing

2021-08-25 19:39 UTC, halitbatur commented on src/components/ContactUs/ContactUs.jsx
> +  function handleChange(evt) {
unconsistincy some functions are arrow and others are old please make all of them arrow functions

2021-08-27 07:54 UTC, halitbatur approved these changes
good work!

2021-08-28 15:42 UTC, udenizdemirbilek approved these changes
Good work Ayshe! Well done!

2021-08-28 18:33 UTC, busesisi approved these changes
Ellerine sağlık Ayshe, great work!

2021-08-31 10:56 UTC, merged